# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Ink Smears
tagline:             'a shelf of thoughts and various hypomnemata'
description:         ''
url:                 http://vqsv.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              R R
  url:               https://vqsv.github.io
  email:             vqsv@icloud.com

# Custom vars
version:             1.0.0
